# Generated by Django 4.2.4 on 2023-09-12 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_patientgroup_workgroup_userlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workgroup",
            name="patient_groups",
        ),
    ]
