# Generated by Django 4.2.4 on 2023-09-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("API", "0006_workgroup_patient_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Clinic Days", "Clinic Days"),
                            ("FHO Clinics", "FHO Clinics"),
                            ("STAT Days", "STAT Days"),
                            ("Holidays", "Holidays"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("weekDays", "Week days with specific times"),
                            ("dateTimeInterval", "Datetime interval"),
                        ],
                        max_length=50,
                    ),
                ),
                ("day", models.CharField(blank=True, max_length=50, null=True)),
                ("from_time", models.TimeField(blank=True, null=True)),
                ("to_time", models.TimeField(blank=True, null=True)),
                ("from_date", models.DateTimeField(blank=True, null=True)),
                ("to_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
