# Generated by Django 4.2.4 on 2023-09-17 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("API", "0007_timeframe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PomeloCredentials",
            new_name="PomeloCredential",
        ),
    ]
