# Generated by Django 4.2.4 on 2023-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0009_timeframe_timezone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeframe",
            old_name="day",
            new_name="end_time_day",
        ),
        migrations.AddField(
            model_name="timeframe",
            name="start_time_day",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
