# Generated by Django 4.2.4 on 2023-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0010_rename_day_timeframe_end_time_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeframe",
            name="chat_on",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
