# Generated by Django 4.2.4 on 2023-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0011_timeframe_chat_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeframe",
            name="chat_on",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
