# Generated by Django 4.2.4 on 2023-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0012_alter_timeframe_chat_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeframe",
            name="chat_on",
        ),
        migrations.AddField(
            model_name="patientgroup",
            name="chat_on",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
