# Generated by Django 4.2.4 on 2023-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0016_pomelocredential_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="pomelocredential",
            name="timezone",
            field=models.CharField(default="America/Toronto", max_length=50),
            preserve_default=False,
        ),
    ]
