# Generated by Django 4.2.4 on 2023-09-29 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0017_pomelocredential_timezone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pomelocredential",
            old_name="timezone",
            new_name="user_timezone",
        ),
    ]
